Stealth Generator Power
DoGyAUT/cd pull request #138
Opened 2017-07-02 12:15 UTC by CDVoidwalker

2017-07-02 16:01 UTC, jrb0001 requested changes
The conditions `cloakgenerator`, `crate-cloak` and `cloakgeneratorpower` should be merged into `cloaked` and `cloaked-bar`.

2017-07-02 16:45 UTC, GraionDilach commented
Disagree with the change requested. It's better to keep them separate for easier override on a per-unit basis like on the Stealth Tank (which shouldn't be able to pick up cloak crates IMO).

2017-07-02 19:13 UTC, CDVoidwalker commented
Well, our crates are all random so I guess it won't have much value to keep those conditions separated

2017-07-03 20:39 UTC, jrb0001 requested changes

2017-07-03 20:39 UTC, jrb0001 commented on rules/defaults.yaml
> +	#TimedConditionBar@cloakedbar: #change it if you want to make it non perma
This seems to be redundant?

2017-07-03 20:39 UTC, jrb0001 commented on rules/forgotten-infantry.yaml
> +		Condition: cloak || cloakgenerator
Should be `cloak || cloak-bar`.

2017-07-03 20:46 UTC, jrb0001 approved these changes

2017-07-03 20:52 UTC, merged