Added new Explosion System For GDI,NOD,CABAL Structures
DoGyAUT/cd pull request #145
Opened 2017-07-12 13:27 UTC by trempler

(Defence/Support Buildings will need work later also units)
Changed repair Intervall from 6 down to 4
Added new Tesla Weapon to SaberCut.

2017-07-12 22:05 UTC, CDVoidwalker requested changes
Looks good to me apart from renaming SabercutLaser to SabercutLaserNew

2017-07-12 22:42 UTC, GraionDilach commented on rules/defaults.yaml
> +		ValidDamageStates: Critical
I'd consider enabling this on Heavy already. TS worked that way.

2017-07-12 22:43 UTC, GraionDilach commented on rules/defaults.yaml
> +		Range: 3c000, 6c000
Redundant zeroes (3c0 is enough)

2017-07-12 22:43 UTC, GraionDilach commented on rules/defaults.yaml
> +		Pieces: 10, 30
The amount worries me. CD is already a performance hog due to the sheer amount of debris spawned.

2017-07-12 22:46 UTC, GraionDilach commented on rules/palettes.yaml
> +		Alpha: 0.8
These values won't work. PaletteFromFile doesn't support alpha values.

You need to create a PaletteFromPaletteWithAlpha derivate if you'd really intend to use alpha. Pretty sure examples already exist in this file.

2017-07-12 22:48 UTC, GraionDilach commented on weapons/cabal-weapons.yaml
> +	Charges: yes
This tag doesn't exist.

2017-07-12 22:49 UTC, GraionDilach commented on weapons/shared-weapons.yaml
> +    Warhead@1Eff: CreateEffect
Messed up indentation.

2017-07-12 22:49 UTC, GraionDilach commented on weapons/shared-weapons.yaml
> +    Warhead@1Eff: CreateEffect
Messed up indentation.

2017-07-12 22:50 UTC, GraionDilach commented on weapons/shared-weapons.yaml
> +	Warhead@6Eff: CreateEffect
This warhead lacks an explosion?!

2017-07-12 22:51 UTC, GraionDilach commented on weapons/shared-weapons.yaml
> +	Warhead@6Eff: CreateEffect
Ah, it's inherited, nevermind this one then.

2017-07-12 22:51 UTC, GraionDilach commented on rules/palettes.yaml
> +		Alpha: 0.8
Note that this applies to all new palette entries.

2017-07-14 12:17 UTC, jrb0001 commented on rules/defaults.yaml
> +		ValidDamageStates: Critical
Fixed.

2017-07-14 12:17 UTC, jrb0001 commented on rules/defaults.yaml
> +		Range: 3c000, 6c000
Fixed.

2017-07-14 12:17 UTC, jrb0001 commented on rules/defaults.yaml
> +		Pieces: 10, 30
Needs feedback from @trempler.

2017-07-14 12:17 UTC, jrb0001 commented on rules/palettes.yaml
> +		Alpha: 0.8
Also applies to existing `PaletteFromFile@alpha2:`. Needs feedback from @trempler.

2017-07-14 12:17 UTC, jrb0001 commented on weapons/cabal-weapons.yaml
> +	Charges: yes
Fixed.

2017-07-14 12:17 UTC, jrb0001 commented on weapons/shared-weapons.yaml
> +    Warhead@1Eff: CreateEffect
Fixed.

2017-07-14 12:17 UTC, jrb0001 commented on weapons/shared-weapons.yaml
> +    Warhead@1Eff: CreateEffect
Fixed.

2017-07-14 12:23 UTC, jrb0001 commented
@CDVoidwalker fixed your point.

2017-07-14 13:31 UTC, trempler commented on rules/defaults.yaml
> +		Pieces: 10, 30
can be adjusted, runs fine here but depends on machine I guess.

2017-07-14 13:32 UTC, trempler commented on rules/palettes.yaml
> +		Alpha: 0.8
Will check coming week or sunday, did not noticed this wont work. maybe not needed for that anyway. So rather removing the Alpha value.

2017-07-14 13:43 UTC, jrb0001 commented on rules/palettes.yaml
> +		Alpha: 0.8
Fixed.

2017-07-14 14:24 UTC, CDVoidwalker approved these changes

2017-07-14 14:39 UTC, merged