Bigpatchtrempler
DoGyAUT/cd pull request #150
Opened 2017-07-13 21:17 UTC by trempler

Added new explosion system for GDI,NOD,CABAL structures
Added new tesla weapon to sabercut and changed it to anti infantry
Added new tesla weapon for dreadfire
Added new laserweapon to core obelisk (Pew pew)
Added new laserlogic to obelisk of darkness (Prism aoe)
Added blue explo for all cabal units.
Added new explosions for ref,harv,silo
Added new abillity totalmeltdown for cabal
Added detection description for venom,hydra,zodiac
Added gasclouds for devils tongue and hailstorm

Fixed visionrange of skirmisher
Fixed GDI service depot hitbox 1x1>3x3

Changed skirmisher ammo
Changed cabal speed upgrade.
Changed cloakingfield of golem down to 3c512
Changed dreadfire name to shockwave
Changed repair Intervall from 6 down to 8
Changed plasma blaster to anti vehicle and adjusted the fx
Changed costs from golem 800$ to 900$
Changed reaper weapon to fit cabal more (clusterrocket)
Changed avatar to no more aoe dmg
Changed zodiac movementspeed from 35 down to 25
Changed fanatic to never explode on death.
Changed cooldown of shadowtrooper drop 3:00 to 4:00
Changed cooldown of napalmstrike 5:00 to 4:00 also reduced direct dmg to vehicle
Changed cooldown of tiberiumbomb 5:00 to 4:00 and reduced direct dmg to buildings
Changed subterranean apc ambush changed e3 count up to 5 and reduced nasol to 3
Changed subapc of industry nod to radartech
Changed raiderbuggy available for all nod factions
Changed artillerystrike to deal 20%less dmg, adjusted aoe, reduced cd from 5:00 to 4:00
Changed emergencyrepairs to repair 30% slower
Changed orca bombingrun to deal 20%less dmg and reduced cd from 5:00 to 4:00
Changed ox-sonic bombing with increased movement and adjusted cd, 3:30 to 2:30

Removed attack bike cloak detection
Removed tiberiumspawn with harvexplo

2017-07-13 21:18 UTC, trempler commented
sry, for other branch still included, forgot to delete it.

2017-07-13 21:23 UTC, GraionDilach commented
I also don't see fixes for anything I pointed out yesterday.

2017-07-14 12:44 UTC, jrb0001 commented
This has to be rebased after https://github.com/DoGyAUT/cd/pull/145 has been merged.

2017-07-14 12:55 UTC, jrb0001 requested changes
In addition to the other comments, naming (https://github.com/DoGyAUT/cd/issues/148) has to be fixed too. Because that has to be done in the refactoring anyway, I suggest moving it to later.

2017-07-14 12:55 UTC, jrb0001 commented on rules/cabal-vehicles.yaml
> +	Inherits@3: ^VehicleC
What does `VehicleC` mean? Should probably be renamed.

2017-07-14 12:55 UTC, jrb0001 commented on rules/defaults.yaml
> +		Weapon: UnitExplodeSmallC
What does `UnitExplodeSmallC` mean? Should probably be renamed.

2017-07-14 12:55 UTC, jrb0001 commented on rules/defaults.yaml
> +		Weapons: SmallDebrisc
What does `SmallDebrisc` mean? Should probably be renamed.

2017-07-14 12:55 UTC, jrb0001 commented on weapons/shared-weapons.yaml
> +UnitExplodeSmallC:
What does `UnitExplodeSmallC` mean? Should probably be renamed.

2017-07-14 12:55 UTC, jrb0001 commented on weapons/shared-weapons.yaml
> +
Whitespace on empty line.

2017-07-14 12:55 UTC, jrb0001 commented on weapons/shared-weapons.yaml
> +
Whitespace on empty line.

2017-07-14 13:04 UTC, jrb0001 commented on rules/cabal-vehicles.yaml
> +	Inherits@3: ^VehicleC
Done.

2017-07-14 13:04 UTC, jrb0001 commented on rules/defaults.yaml
> +		Weapon: UnitExplodeSmallC
Done.

2017-07-14 13:04 UTC, jrb0001 commented on rules/defaults.yaml
> +		Weapons: SmallDebrisc
Done.

2017-07-14 13:04 UTC, jrb0001 commented on weapons/shared-weapons.yaml
> +UnitExplodeSmallC:
Done.

2017-07-14 13:04 UTC, jrb0001 commented on weapons/shared-weapons.yaml
> +
Done.

2017-07-14 13:04 UTC, jrb0001 commented on weapons/shared-weapons.yaml
> +
Done.

2017-07-14 13:05 UTC, jrb0001 approved these changes

2017-07-14 14:50 UTC, CDVoidwalker approved these changes
Looks good to me

2017-07-14 14:52 UTC, merged