Ganonpatch
DoGyAUT/cd pull request #171
Opened 2017-07-25 16:59 UTC by trempler

GDI:
    Zone Command Drop:
    remove the commando from it
    change the drop to drop 3 Zone Troopers and 3 Zone Raiders
    Titan Mech Drop:
    remove the Titan MKII from it
    Drops 4 Titans in total
    Poseidon Tank Drop:
    remove Poseidon tank from it
    let it drop 3 Grizzly Tanks in total
    renamed to Grizzly Tank Drop
    remove the ability from Steel Talons and added it to GDF
    it now now available via lockingin GDF as a subfacion while having a Techlab
    APC Tooltip updated: can detect stealth
    Vulture Tooltip updated: can detect stealth
    Zone Commander:
    buildable for ZOCOM:
    cost to 4000$
    available upon techlab
    buildlimit of 1
    heavy crush class
    renamed to Colonel Mobius
    added selfhealing
    damage stats:
            Damage: 150
            Versus:
                Infantry: 100
                Cyborg: 100
                Vehicle: 100
                Aircraft: 100
                Building: 100
    Artillery Strike
    Artillery_Beacon speed from 424 to 150
    Titan:
    new weapon called TitanAP
    same stats as the 122mmAP weapon but instead of 9c559 to 11c0 attackrange
    HP from 1440 to 1200
    Zone Marine:
    ZoneMarineGun reloadspeed from 60 to 50
    cost from 200$ to 175$
    Orca-F2:
    cost from 1200$ to 1350$
    reloadspeed from 160 to 120
    Hellfire Missiles:
    move it to Steel Talon Dropship bay (the ability was originally for Steel Talons)
    renamed it from A huge Rocketbombardment to Hellfire Missiles
    speed of the Kodiak from 68 to 150
    Condor:
    Movementspeed from 200 to 220
    damage of CondorBomb from 700 to 800
    damage stats:
            Versus:
                Infantry: 100
                Cyborg: 100
                Vehicle: 100
                Aircraft: 100
                Building: 100
    Hover MLRS:
    HoverMRLSMissileAA:
    inacccuracy from 0c724 to 0c362
    spread from 0c1 to 0c362
    reloadspeed from 200 to 150

    Nod:
    Paraunitdrop Carryall not targetable anymore
    Rookies from 60$ to 70$ (the propaganda nod upgraded rookies from 30$ to 35$)
    Flame Turret:
    vanilla: damage from 40 to 45
    bluehellinferno: damage from 50 to 65
    tiberium warheads: damage to 55
    Industry Nod:
    Swaping Gattlingturret with Flameturret, adding Samside aswell
    Flameturret will be effected by Tiberiums Warheads Upgrade (kinda like the devils tongue)
    Sam Site shall also improve its damage via Tiberium Warheads
    upgrade increases the damage from 150 to 175
    Havocs are targetable again
    Hydra from 1400$ to 1650$
    changed cloudspawning rate of Devil Tognue, Hailstorm and Flame Turret from 2 clouds per projectile to 1 cloud per projectile
    Avatar movementspeed to 70
    Attackbike attackrange from 8c497 to 9c559
    revealsshorud from 9c921 to 10c921

    Cabal:
    Shockwave:
    burst from 3 to 2 (now shoots 4 times instead of 6)
    Reaper:
    attackrange from 8c497 to 9c559
    Total Meltdown fixed
    reloadspeed from 10 to 10000
    Renaming Upgrades:
    Teleporter
    "Experimental Phase Jump"
    Vision Uplink
    "Optics Augmentation"
    Alloyed Chassis
    "Organic Polymers" or "Cybernetic Legs"
    Advanced Platings
    "Fullerene Construction Techniques"

2017-07-25 18:05 UTC, CDVoidwalker submitted a review, later dismissed
Seems to be good, although I'd not reccomend adding tib to SAM just because it's missile, making every second weapon gain profit from this upgrade makes it way less unique

2017-08-01 00:10 UTC, jrb0001 commented on rules/gdi-infantry.yaml
> +    SelfHealing:
Indentation

2017-08-01 00:25 UTC, jrb0001 requested changes
Needs bigger fixes.

2017-08-01 00:25 UTC, jrb0001 commented on rules/gdi-structures.yaml
> +        Prerequisites: gaarmory, ~upgrade.gdf
Indentation.

2017-08-01 00:25 UTC, jrb0001 commented on rules/gdi-structures.yaml
>  		LongDesc: Drops a Zone Commander with a squad of 2 Troopers and 2 Raiders.
Outdated.

2017-08-01 00:25 UTC, jrb0001 commented on rules/gdi-structures.yaml
> +	ParatroopersPower@poseidon:
Update tooltip of building.

2017-08-01 00:25 UTC, jrb0001 commented on rules/gdi-structures.yaml
> +		Description: Zone Troop Drop
Update tooltip of building.

2017-08-01 00:25 UTC, jrb0001 commented on rules/gdi-structures.yaml
> -	ParatroopersPower@poseidon:
Update tooltip of building.

2017-08-01 00:25 UTC, jrb0001 commented on rules/gdi-structures.yaml
> +	AirstrikePower@HellfireMissilesStrikePower:
Update tooltip of building.

2017-08-01 00:25 UTC, jrb0001 commented on rules/nod-aircraft.yaml
> +    Inherits@FeatureAutotargetBuilding: ^FeatureAutotargetBuilding3
Indentation. (x4)

2017-08-01 00:25 UTC, jrb0001 commented on rules/nod-aircraft.yaml
> +    -Targetable@TargettypeGrounded:
Indentation. (x2)

2017-08-01 00:25 UTC, jrb0001 commented on rules/nod-structures.yaml
> +	SpawnActorPower@subambush:
Update tooltip of building.

2017-08-01 00:25 UTC, jrb0001 commented on rules/nod-support.yaml
> +#	GrantConditionOnPrerequisite@upgrade1:
Remove completely?

2017-08-01 00:25 UTC, jrb0001 commented on rules/nod-support.yaml
> +#	Cloak:
Remove completely?

2017-08-01 00:25 UTC, jrb0001 commented on rules/nod-support.yaml
> +    Power:
Indentation.

2017-08-01 00:25 UTC, jrb0001 commented on rules/nod-support.yaml
> +    GrantConditionOnPrerequisite@upgrade3:
Indentation.

2017-08-01 00:25 UTC, jrb0001 commented on rules/nod-support.yaml
> +    GrantConditionOnPrerequisite@upgrade1:
Indentation.

2017-08-01 00:25 UTC, jrb0001 commented on rules/nod-support.yaml
> +    Cloak:
Indentation.

2017-08-01 00:25 UTC, jrb0001 commented on rules/nod-support.yaml
> +#	GrantConditionOnPrerequisite@upgrade1:
Remove completely?

2017-08-01 00:25 UTC, jrb0001 commented on rules/nod-support.yaml
> +#	Cloak:
Remove completely?

2017-08-01 00:25 UTC, jrb0001 commented on weapons/gdi-weapons.yaml
> +        Versus:
Indentation.

2017-08-01 00:25 UTC, jrb0001 commented on weapons/gdi-weapons.yaml
> +        Versus:
Indentation.

2017-08-01 00:25 UTC, jrb0001 commented on weapons/nod-weapons.yaml
> +    BurstDelay: 20
Indentation. (x2)

2017-08-01 00:25 UTC, jrb0001 commented on weapons/nod-weapons.yaml
> +    Warhead@2Eff: CreateEffect
Indentation.

2017-08-01 00:25 UTC, jrb0001 commented on weapons/nod-weapons.yaml
> +    WarheadAS: SpawnActor
Indentation.

2017-08-01 00:25 UTC, jrb0001 commented on weapons/nod-weapons.yaml
> +        TerrainHeightAware: true
Indentation.

2017-08-01 00:25 UTC, jrb0001 commented on rules/nod-vehicles.yaml
> +    WithVoxelBody:
Indentation.

2017-08-01 00:25 UTC, jrb0001 commented on rules/nod-vehicles.yaml
> +    GrantConditionOnPrerequisite@upgrade1:
Indentation.

2017-08-01 00:25 UTC, jrb0001 commented on rules/nod-support.yaml
> +    WithMuzzleOverlay:
Indentation.

2017-08-01 00:25 UTC, jrb0001 commented on rules/nod-support.yaml
> +    GrantConditionOnPrerequisite@upgrade1:
Indentation.

2017-08-01 00:25 UTC, jrb0001 commented on rules/gdi-infantry.yaml
> +    HitShape:
Indentation.

2017-08-01 00:25 UTC, jrb0001 commented on rules/gdi-infantry.yaml
> +    Valued:
Indentation.

2017-08-01 00:25 UTC, jrb0001 commented on rules/gdi-infantry.yaml
> +        BuildLimit: 1
Indentation.

2017-08-01 00:26 UTC, jrb0001 commented
That list of changes should be included in the commit message and one commit per change would be much better.

2017-08-01 00:28 UTC, jrb0001 commented
Needs second thorough review after fixups. @CDVoidwalker you might want to remove your positive review and redo it later...

2017-08-01 08:00 UTC, CDVoidwalker commented
True, I'm forgetting about indentation and still I'm not used to making tooltips as we've been avoiding it for quite a bit, so it looked fine for me

2017-08-01 10:50 UTC, GraionDilach commented on rules/gdi-structures.yaml
> +		Description: Zone Troop Drop
Also we don't say "Troop Drop" in English. Team Call maybe.

2017-08-05 19:25 UTC, jrb0001 commented on rules/gdi-structures.yaml
> +	ParatroopersPower@poseidon:
done.

2017-08-05 19:25 UTC, jrb0001 commented on rules/gdi-structures.yaml
>  		LongDesc: Drops a Zone Commander with a squad of 2 Troopers and 2 Raiders.
done.

2017-08-05 19:25 UTC, jrb0001 commented on rules/gdi-structures.yaml
> +		Description: Zone Troop Drop
done.

2017-08-05 19:25 UTC, jrb0001 commented on rules/gdi-structures.yaml
> -	ParatroopersPower@poseidon:
done.

2017-08-05 19:25 UTC, jrb0001 commented on rules/gdi-structures.yaml
> +	AirstrikePower@HellfireMissilesStrikePower:
done.

2017-08-05 19:25 UTC, jrb0001 commented on rules/nod-aircraft.yaml
> +    Inherits@FeatureAutotargetBuilding: ^FeatureAutotargetBuilding3
done.

2017-08-05 19:25 UTC, jrb0001 commented on rules/nod-aircraft.yaml
> +    -Targetable@TargettypeGrounded:
done.

2017-08-05 19:25 UTC, jrb0001 commented on rules/nod-structures.yaml
> +	SpawnActorPower@subambush:
done.

2017-08-05 19:25 UTC, jrb0001 commented on rules/nod-support.yaml
> +    Power:
done.

2017-08-05 19:25 UTC, jrb0001 commented on rules/nod-support.yaml
> +#	GrantConditionOnPrerequisite@upgrade1:
done.

2017-08-05 19:25 UTC, jrb0001 commented on rules/nod-support.yaml
> +    GrantConditionOnPrerequisite@upgrade3:
done.

2017-08-05 19:25 UTC, jrb0001 commented on rules/nod-support.yaml
> +#	Cloak:
done.

2017-08-05 19:25 UTC, jrb0001 commented on rules/nod-support.yaml
> +    GrantConditionOnPrerequisite@upgrade1:
done.

2017-08-05 19:26 UTC, jrb0001 commented on rules/nod-support.yaml
> +    Cloak:
done.

2017-08-05 19:26 UTC, jrb0001 commented on rules/nod-support.yaml
> +#	GrantConditionOnPrerequisite@upgrade1:
done.

2017-08-05 19:26 UTC, jrb0001 commented on rules/nod-support.yaml
> +#	Cloak:
done.

2017-08-05 19:26 UTC, jrb0001 commented on rules/nod-support.yaml
> +    GrantConditionOnPrerequisite@upgrade1:
done.

2017-08-05 19:26 UTC, jrb0001 commented on rules/nod-support.yaml
> +    WithMuzzleOverlay:
done.

2017-08-05 19:26 UTC, jrb0001 commented on weapons/gdi-weapons.yaml
> +        Versus:
done.

2017-08-05 19:26 UTC, jrb0001 commented on weapons/gdi-weapons.yaml
> +        Versus:
done.

2017-08-05 19:26 UTC, jrb0001 commented on weapons/nod-weapons.yaml
> +    BurstDelay: 20
done.

2017-08-05 19:26 UTC, jrb0001 commented on weapons/nod-weapons.yaml
> +    Warhead@2Eff: CreateEffect
done.

2017-08-05 19:26 UTC, jrb0001 commented on weapons/nod-weapons.yaml
> +    WarheadAS: SpawnActor
done.

2017-08-05 19:26 UTC, jrb0001 commented on weapons/nod-weapons.yaml
> +        TerrainHeightAware: true
done.

2017-08-05 19:26 UTC, jrb0001 commented on rules/nod-vehicles.yaml
> +    GrantConditionOnPrerequisite@upgrade1:
done.

2017-08-05 19:26 UTC, jrb0001 commented on rules/nod-vehicles.yaml
> +    WithVoxelBody:
done.

2017-08-05 19:26 UTC, jrb0001 commented on rules/gdi-infantry.yaml
> +        BuildLimit: 1
done.

2017-08-05 19:27 UTC, jrb0001 commented on rules/gdi-infantry.yaml
> +    Valued:
done.

2017-08-05 19:27 UTC, jrb0001 commented on rules/gdi-infantry.yaml
> +    HitShape:
done.

2017-08-05 19:27 UTC, jrb0001 commented on rules/gdi-infantry.yaml
> +    SelfHealing:
done.

2017-08-05 19:35 UTC, jrb0001 approved these changes

2017-08-05 20:43 UTC, CDVoidwalker approved these changes

2017-08-05 23:10 UTC, merged